### ISSUE TITLE
Problems to run code

### ISSUE THREAD

**Issue by NacAlain** [fogleman/axi#1]
Hi,
Code looks great but I got problems to run it. Here the warnings I got 
f:\Program Files (x86)\Python 3.5\python.exe" F:/axidraw/axi/examples/dragon_curve.py
Traceback (most recent call last):
  File "F:/axidraw/axi/examples/dragon_curve.py", line 15, in <module>
    main(12)
  File "F:/axidraw/axi/examples/dragon_curve.py", line 12, in main
    axi.draw(drawing)
  File "f:\axidraw\axi\axi\util.py", line 10, in draw
    d = Device()
  File "f:\axidraw\axi\axi\device.py", line 61, in __init__
    self.configure()
  File "f:\axidraw\axi\axi\device.py", line 72, in configure
    self.command('SC', 4, pen_up_position)
  File "f:\axidraw\axi\axi\device.py", line 89, in command
    self.serial.write(line + '\r')
  File "F:\Program Files (x86)\Python 3.5\lib\site-packages\serial\serialwin32.py", line 308, in write
    data = to_bytes(data)
  File "F:\Program Files (x86)\Python 3.5\lib\site-packages\serial\serialutil.py", line 63, in to_bytes
    raise TypeError('unicode strings are not supported, please encode to bytes: {!r}'.format(seq))
TypeError: unicode strings are not supported, please encode to bytes: 'SC,4,19800\r'

Process finished with exit code 1
I hope you could help me to resolve it, thanks

**Comment by fogleman** [comment]
Try Python 2.7

**Comment by NacAlain** [comment]
Many thanks,it's working.
