### ISSUE TITLE
OSError: dlopen() failed to load a library: cairo / cairo-2

### ISSUE THREAD

**Issue by mpgilliam** [fogleman/axi#9]
installed axi on MacOS High Sierra 10.13.
tried to run the dragon curve demo and getting the error below.

$ python dragon_curve.py
Traceback (most recent call last):
  File "dragon_curve.py", line 1, in <module>
    import axi
  File "/Users/IWU/GitHub/axi/axi/__init__.py", line 2, in <module>
    from .drawing import Drawing
  File "/Users/IWU/GitHub/axi/axi/drawing.py", line 10, in <module>
    import cairocffi as cairo
  File "/anaconda2/envs/axidraw/lib/python2.7/site-packages/cairocffi/__init__.py", line 41, in <module>
    cairo = dlopen(ffi, 'cairo', 'cairo-2')
  File "/anaconda2/envs/axidraw/lib/python2.7/site-packages/cairocffi/__init__.py", line 38, in dlopen
    raise OSError("dlopen() failed to load a library: %s" % ' / '.join(names))
OSError: dlopen() failed to load a library: cairo / cairo-2

**Comment by mpgilliam** [comment]
Figured out I needed to install cairo in root and not the conda environment. This can be closed.
